### ISSUE TITLE
Tyrannosaurus vs. Triceratops 

### ISSUE THREAD

**Issue by daretmavi** [ElCeejo/paleotest#2]
Hi,

I got an Error while several Tyrannosauruses fight several Triceratopses :)

```
AsyncErr: ServerThread::run Lua: Runtime error from mod 'default' in callback luaentity_Step(): ...minetest/games/Planet_alive/mods/lib_api/mobkit/init.lua:1151: attempt to index local 'rot' (a nil value)
stack traceback:
	...minetest/games/Planet_alive/mods/lib_api/mobkit/init.lua:1151: in function 'func'
	...minetest/games/Planet_alive/mods/lib_api/mobkit/init.lua:741: in function 'execute_queues'
	...minetest/games/Planet_alive/mods/lib_api/mobkit/init.lua:959: in function 'stepfunc'
	/home/USER/.minetest/mods/paleotest/api/api.lua:88: in function 'old_step'
	/home/USER/.minetest/mods/paleotest/api/register.lua:53: in function </home/USER/.minetest/mods/paleotest/api/register.lua:52>
```

**Comment by ElCeejo** [comment]
To the best of my knowledge this is a mobkit issue that I already made an issue for on the mobkit github page. I think the issue may be due to lag though which I'm currently working on reducing.

**Comment by ElCeejo** [comment]
With this new update reduces lag, so this bug _should_ disappear. I'll leave it open for another week and if it doesn't occur again it'll be closed.

**Comment by daretmavi** [comment]
Thanx for info. Looks like it is working.

Could you add mob_core to content db?

Great mod by the way :+1:
