### ISSUE TITLE
Tryranosauruses NOT moving after hatching.

### ISSUE THREAD

**Issue by LandonAConway** [ElCeejo/paleotest#4]
The tyrannosaurus, and other dinosaurs, are not moving. What am I missing?

**Comment by ElCeejo** [comment]
Interesting. I can't seem to re-create this in any of my worlds. Are you sure you have the latest version and they aren't set to the "Stand" order?

**Comment by LandonAConway** [comment]
I'm using Minetest version 5.2.0. The mobs are just standing there!

**Comment by LandonAConway** [comment]
> Interesting. I can't seem to re-create this in any of my worlds. Are you sure you have the latest version and they aren't set to the "Stand" order?

I have updated Minetest to version 1.3.0 and the problem persists.

**Comment by ElCeejo** [comment]
Try updating Mob Core to the latest version.

**Comment by LandonAConway** [comment]
I have already done this. It's not working.

**Comment by LandonAConway** [comment]
> Try updating Mob Core to the latest version.

Yes. So, I tried making a new world that using no mods except for the builtin mods, and then enabled "mobkit", "mob_core", and "paleotest". I re-downloaded all three of those to update them and made sure my Minetest version was also up to date (Minetest v5.3.0). Still, they won't move. I placed 3 tyrannosaurus eggs next to a torch. They hatched, but, like I said, they don't do anything but stand there. But they do become adults. But, the adults also just stand there.

**Comment by ElCeejo** [comment]
Even after removing my dev versions of Mob Core and PaleoTest and using the public versions I can't seem to recreate this. It seems like this is an issue on your end. I've tried hatching them at day and night, near a player and far from a player, and I can't recreate this issue.

**Comment by LandonAConway** [comment]
I must be doing something wrong. I know I have all of the mods up to date? What version of Minetest are you using? Are you on Linux? I'm on windows 10! I dont know why there are problems? Send me the links to the mod depends. Maybe I'm downloading them from the wrong sources!

**Comment by ElCeejo** [comment]
I'm on Windows 10 as well. As long as you're downloading from ContentDB or the forum post then it should be the latest version.

**Comment by LandonAConway** [comment]
Thats where I'm getting them from. Are you using dev Minetest?

**Comment by ElCeejo** [comment]
Seems like this issue did indeed affect some mobs. Interestingly, Tyrannosaurus was not one of them. But as of these latest commits this issue shouldn't persist.
