### ISSUE TITLE
Crash attempt to index field 'lastvelocity' (a nil value)

### ISSUE THREAD

**Issue by Tviljan** [ElCeejo/paleotest#9]
AsyncErr: ServerThread::run Lua: Runtime error from mod '??' in callback luaentity_Step(): ....3.0-win64\bin\..\games\minetestxyz\mods\mobkit\init.lua:930: attempt to index field 'lastvelocity' (a nil value)
stack traceback:
	....3.0-win64\bin\..\games\minetestxyz\mods\mobkit\init.lua:930: in function 'old_step'
	...bin\..\games\minetestxyz\mods\paleotest/api/register.lua:53: in function <...bin\..\games\minetestxyz\mods\paleotest/api/register.lua:52>

Mobkit release = 2339
Paleotest release = 5472

This happens soon after starting server on survival

**Comment by ElCeejo** [comment]
Your mobkit version is outdated.
